name    'andyshinn-atomic'
version '0.1.0'
source 'http://github.com/andyshinn/puppet-atomic'
author 'andyshinn'
license 'Apache License, Version 2.0'
summary 'Setup the Atomicorp Free RPM Repository'
description 'Setup the Atomicorp Free RPM Repository on CentOS and RHEL variants'
project_page 'http://github.com/andyshinn/puppet-atomic'
